# Generated by Django 3.0.3 on 2020-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('AP', 'Antipasto'), ('FC', 'Primo'), ('SC', 'Secondo'), ('SD', 'Contorno'), ('DT', 'Dessert')], default='AP', max_length=2)),
                ('author', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('ED', 'Facile'), ('MD', 'Media'), ('HD', 'Difficile')], default='MD', max_length=2)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=120)),
            ],
        ),
    ]
