# Generated by Django 3.0.3 on 2020-03-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Antipasto', 'Antipasto'), ('Primo', 'Primo'), ('Secondo', 'Secondo'), ('Contorno', 'Contorno'), ('Dessert', 'Dessert')], default='Antipasto', max_length=120)),
                ('difficulty', models.CharField(choices=[('Bassa difficoltà', 'Bassa difficoltà'), ('Media difficoltà', 'Media difficoltà'), ('Alta difficoltà', 'Alta difficoltà')], default='Media difficoltà', max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(to='ingredients.Ingredient')),
            ],
        ),
    ]
