# Generated by Django 3.0.3 on 2020-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
        migrations.DeleteModel(
            name='IngredientQuantity',
        ),
    ]
