# Generated by Django 3.0.3 on 2020-03-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('ED', 'Easy'), ('MD', 'Middle'), ('HD', 'Hard')], default='MD', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nationality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('FC', 'First Course'), ('SC', 'Second Course'), ('SD', 'Side Dish'), ('DT', 'Dessert')], default='AP', max_length=2),
        ),
    ]
