# Generated by Django 3.0.3 on 2020-03-06 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Bassa difficoltà', 'Easy'), ('Media difficoltà', 'Middle'), ('Alta difficoltà', 'Hard')], default='Media difficoltà', max_length=120),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Antipasto', 'Appetizer'), ('Primo', 'First Course'), ('Secondo', 'Second Course'), ('Contorno', 'Side Dish'), ('Dessert', 'Dessert')], default='Antipasto', max_length=120),
        ),
    ]
