# Generated by Django 3.0.3 on 2020-03-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200307_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('-', '-'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=2),
        ),
    ]
